### ISSUE TITLE
Field validation problem (required to make title change)

### ISSUE THREAD

**Issue by tristantbg** [jongacnik/kirby-index-field#1]
(Thank you for this great plugin, very useful in my case.)

The page with the field can't be modified because of a validation error.

![capture d ecran 2017-08-16 a 09 47 29](https://user-images.githubusercontent.com/4832038/29352776-453e472a-8268-11e7-9b0c-12e2f00c3ef9.png)

I made it work by adding this line to the content text file :

----

Pageindex:

**Comment by jongacnik** [comment]
Good catch, fixed!
