### ISSUE TITLE
set default column to order index with

### ISSUE THREAD

**Issue by sonn-gamm** [jongacnik/kirby-index-field#4]
Hi, amazing plugin.

Is there a way to set a default column to use for ordering the index? 

I tried to use

```
pages:
  sort: column-value asc
```

but did not change anything. Am I missing something?

If I put the field I want to use to sort the content with as first column element, still the plugin does not order entries by that.

Thanks,
af

**Comment by jongacnik** [comment]
Thanks, good call! Just updated the table structure to allow for initial sort by first column #5 

I'm sure being able to set asc/desc or to specify a column to initially sort by will be handy, but sorting-by-first hopefully serves as a workaround til I get around to making it a bit more robust.

**Comment by sonn-gamm** [comment]
Thanks for quickly providing this! It works well.
